version = 1

test_patterns = ["**/*_test.go"]

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "go"
enabled = true

[analyzers.meta]
import_root = "github.com/loopholelabs/frisbee"

[[transformers]]
name = "gofmt"
enabled = true