name: Tests and Benchmarks

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
          cache: true
      - name: Run Tests
        run: go test -v ./...
  tests-race:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
          cache: true
      - name: Test with Race Conditions
        run: go test -race -v ./...
        timeout-minutes: 15
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
          cache: true
      - name: Benchmark
        run: go test -run=^$ -bench=. -v ./...
  benchmarks-race:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
          cache: true
      - name: Benchmark with Race Conditions
        run: go test -run=^$ -bench=. -race -timeout 30m -v ./...
        timeout-minutes: 30